# Generated by Django 4.1.3 on 2023-04-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webcam", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.ImageField(upload_to="video/")),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
